config/routes.rb
Rails.application.routes.draw do
    resources :slidedecks
  resources :notes
  resources :tutorials
  resources :presentations
  resources :grades
  resources :submissions
  resources :assignments
  resources :abouts
  resources :projects
  resources :courses
  resources :posts do 
    resources :responses
  end

  get 'pages/gradebook'
    get 'pages/graded'

  get 'pages/accounts'
  get 'usergrades' => "submissions#usergrades"
 
  devise_for :users
   match 'users/:id' => 'users#index', via: :get
# or 
get 'users/:id' => 'users#index'
# or
resources :users, only: [:index]

root :to => 'abouts#index'  
resources :lessons
  get 'pages/policies'

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
	has_many :learnings
	has_many :lessons, :through => :learnings
	belongs_to :user
	has_many :objectives, :dependent => :destroy
	has_many :classactivitys, :dependent => :destroy

	has_attached_file :attachment
	do_not_validate_attachment_file_type :attachment

	accepts_nested_attributes_for :objectives, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :classactivitys, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  before_action :set_tutorial, only: [:show, :edit, :update, :destroy]
    before_filter :check_user, only: [:edit, :update, :destroy]

  before_filter :authorize_admin, only: [:new, :create, :destroy, :edit]

  # GET /tutorials
  # GET /tutorials.json
  def index
    @tutorials = Tutorial.includes(:lessons).order('lessons.week ASC')
  end

  # GET /tutorials/1
  # GET /tutorials/1.json
  def show
  end

  # GET /tutorials/new
  def new
    @tutorial = Tutorial.new
    @tutorial.objectives.build

  end

  # GET /tutorials/1/edit
  def edit
  end

  # POST /tutorials
  # POST /tutorials.json
  def create
    @tutorial = Tutorial.new(tutorial_params)

    respond_to do |format|
      if @tutorial.save
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully created.' }
        format.json { render :show, status: :created, location: @tutorial }
      else
        format.html { render :new }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutorials/1
  # PATCH/PUT /tutorials/1.json
  def update
    respond_to do |format|
      if @tutorial.update(tutorial_params)
        format.html { redirect_to @tutorial, notice: 'Tutorial was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutorial }
      else
        format.html { render :edit }
        format.json { render json: @tutorial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutorials/1
  # DELETE /tutorials/1.json
  def destroy
    @tutorial.destroy
    respond_to do |format|
      format.html { redirect_to tutorials_url, notice: 'Tutorial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutorial
      @tutorial = Tutorial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutorial_params
      params.require(:tutorial).permit(:name, :content, :video, {lesson_ids: []}, :lesson, :lesson_id, :attachment, objectives_attributes: [:id, :content, :_destroy], classactivitys_attributes: [:id, :content, :_destroy])
    end
    def check_user
      if current_user == authorize_admin
        redirect_to root_url, alert: "You don't have permission to do that!"
      end 
    end
end

app/helpers/tutorials_helper.rb
module TutorialsHelper
end

app/views/tutorials/_classactivity_fields.html.erb
<fieldset>
    <%= f.label :content, "Class Activity" %><br />
    <%= f.text_area :content, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>


</fieldset>

app/views/tutorials/_form.html.erb
<%= simple_form_for(@tutorial) do |f| %>
  <%= f.error_notification %>
  <div class="third-form-group">
    <%= f.input :name, class: 'form-control' %>
     <%= f.input :video, class: 'form-control' %>
    </div>
    <div class="second-form-group">
  <h2>Tutorial Objectives</h2>
    <%= f.fields_for :objectives do |builder| %>
    <%= render 'objective_fields', f:builder %>
    <% end %>
  <%= link_to_add_fields "Add Objective", f, :objectives, class: "btn btn-mini btn-info" %>
</div>
<div class="third-form-group">
  <h2>Class Activities</h2>
  <%= f.fields_for :classactivitys do |builder| %>
  <%= render 'classactivity_fields', f:builder %>
  <% end %>
  <%= link_to_add_fields "Add Activity", f, :classactivitys, class: "btn btn-mini btn-info" %>
</div>
<div class="second-form-group">
<h2>Add Attachment (if applicable)</h2>
      <%= f.label :attachment %>
      <%= f.file_field :attachment, :class => "form-control-file", class: "form-control" %>
</div>
<div class="second-form-group">
    <%= f.label :content %>
    <%= f.text_area :content, rows: "30", class: 'form-control' %>
   
    
</div>

  <div class="third-form-group">
<h2>Connect Tutorial with a Lesson</h2>

        <%= hidden_field_tag "tutorial[lesson_ids][]", nil %>
        <% Lesson.all.each do |lesson| %>
          <%= check_box_tag "tutorial[lesson_ids][]", lesson.id, @tutorial.lesson_ids.include?(lesson.id), id: dom_id(lesson) %>
          <%= label_tag dom_id(lesson), lesson.name %> | <%= lesson.date %>
          <br />

        <% end %>
    </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tutorials/_objective_fields.html.erb
<fieldset>
    <%= f.label :content, "Objective" %><br />
    <%= f.text_area :content, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: "remove_fields" %>

</fieldset>

app/views/tutorials/edit.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-2">
<h1>Editing Tutorial</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutorial %> |
<%= link_to 'Back', tutorials_path %>
</div>
</div>

app/views/tutorials/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1><%= image_tag 'tutorial.png' %> Tutorials and Other Resources</h1>
<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Tutorial Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutorials.each_with_index do |tutorial, i| %>
      <tr>
        <td><%= (i+1) %>.</td>
        <td><%= link_to tutorial.name, tutorial %></td>
      
        <td><%= link_to tutorial do %>
              <i class="material-icons">pageview</i>
          <% end %></td>
      <% if current_user.try(:admin?) %>

        <td><%= link_to 'Edit', edit_tutorial_path(tutorial) %></td>
        <td><%= link_to 'Destroy', tutorial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>
<% if current_user.try(:admin?) %>

<%= link_to 'New Tutorial', new_tutorial_path %>
<% end %>
</div>

app/views/tutorials/new.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-2">
<h1>New Tutorial</h1>

<%= render 'form' %>

<%= link_to 'Back', tutorials_path %>
</div>
</div>

app/views/tutorials/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<div class="col-md-8">
  <h1><%= image_tag 'tutorial.png' %> <%= @tutorial.name %></h1>
<% if current_user.try(:admin?) %>

  <%= link_to 'Edit', edit_tutorial_path(@tutorial) %> |
<%= link_to 'Back', tutorials_path %>
<% end %>
 <% if @tutorial.video? %>
<div class="video-container">
  	<%= @tutorial.video.html_safe %>
 </div>
 <% end %>
 <h3><%= image_tag 'bullets.png' %> Tutorial Objectives:</h3>
		<ul>
			<% for objective in @tutorial.objectives %>
			<li><%= objective.content %></li>
		<% end %>
		</ul>
	<div class="tutorial-content">
		<%= simple_format @tutorial.content.html_safe %>
	</div>
 
		<h3><%= image_tag 'checks.png' %> To Do:</h3>
		<ol>
		<% for classactivity in @tutorial.classactivitys.order(:created_at) %>
		<li><%= classactivity.content.html_safe %></li>
		<% end %>
		</ol>
<h3><%= image_tag 'attachments.png' %> Tutorial Attachments</h3>
            <% if @tutorial.attachment? %>
                <ul><li><a target=_blank href=" <%= @tutorial.attachment.url %>"><strong><%= @tutorial.attachment.original_filename %></strong></a></li></ul>
                <% else %>
                <li>No Document(s) Attached!</li>
              <% end %>
              <br>
         <%= link_to "Submit Assignment", new_submission_path, class: "btn btn-green" %>
 </div>

  <div class="col-md-4 projects-right">
  	
		<div class="padding-right">

			<h1>What is this tutorial related to?</h1>
			<p style = "font-size: 1.2rem !important; line-height: 2rem !important">This tutorial or resource is pertinent to:</p>
			<% for @lesson in @tutorial.lessons %>
			<ul>
				<li style = "font-size: 1.2rem !important; line-height: 2rem !important"><%= link_to @lesson.name, @lesson %>", which was discussed on <%= @lesson.date %> in week <%= @lesson.week %> of the semester.</li>
		     </ul>
      <% end %>
		</div>
			
	</div>
<br>
<br>


</div>