config/routes.rb
Rails.application.routes.draw do
    resources :slidedecks
  resources :notes
  resources :tutorials
  resources :presentations
  resources :grades
  resources :submissions
  resources :assignments
  resources :abouts
  resources :projects
  resources :courses
  resources :posts do 
    resources :responses
  end

  get 'pages/gradebook'
    get 'pages/graded'

  get 'pages/accounts'
  get 'usergrades' => "submissions#usergrades"
 
  devise_for :users
   match 'users/:id' => 'users#index', via: :get
# or 
get 'users/:id' => 'users#index'
# or
resources :users, only: [:index]

root :to => 'abouts#index'  
resources :lessons
  get 'pages/policies'

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :course
	has_many :learnings
	has_many :lessons, :through => :learnings
	has_many :deliverables, :dependent => :destroy
	has_many :rubrics, :dependent => :destroy
	has_many :related, :dependent => :destroy
	belongs_to :user

	accepts_nested_attributes_for :deliverables, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :rubrics, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :related, :reject_if => lambda { |a| a[:description].blank? }, :allow_destroy => true
    default_scope { order('name') } 

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  before_filter :authorize_admin, only: [:new, :create, :destroy, :edit]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all.reorder(due: :asc)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show

  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.deliverables.build
    @project.rubrics.build
    @project.related.build
  end

  # GET /projects/1/edit
  def edit
  
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id 
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit({lesson_ids: []},:id, :due, :lesson, :user_id, :name, :description, :project_id, rubrics_attributes: [:id, :description, :_destroy], deliverables_attributes: [:id, :description, :_destroy], related_attributes: [:description, :id, :_destroy])
    end

     def check_user
       if current_user == authorize_admin
        redirect_to root_url, alert: "Nice try! Access Denied! :)", class: 'alert alert-danger'
      end 
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_deliverable_fields.html.erb
<fieldset>
    <%= f.label :description, "Deliverable" %><br />
    <%= f.text_area :description, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>   
</fieldset>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="second-form-group">
    <%= f.label :due %><br>
    <%= f.date_select :due, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", rows: "6" %>
  </div>
  <div class="second-form-group">
    <h2>Deliverables</h2>
        <%= f.fields_for :deliverables do |builder| %>
        <%= render 'deliverable_fields', f:builder %>
          <% end %>
      <%= link_to_add_fields "Add Deliverable", f, :deliverables, class: "btn btn-mini btn-info add-link" %>
  </div>

  <div class="third-form-group">
  <h2>Grading Criteria</h2>
      <%= f.fields_for :rubrics do |builder| %>
        <%= render 'rubric_fields', f:builder %>
      <% end %>

      <%= link_to_add_fields "Add Criteria", f, :rubrics, class: "btn btn-mini btn-info" %>
  </div>
  <div class="second-form-group">
  <h2 style = "text-align: left">What lessons is this project related to?</h2>
        <%= hidden_field_tag "project[lesson_ids][]", nil %>
        <% Lesson.all.each do |lesson| %>
          <%= check_box_tag "project[lesson_ids][]", lesson.id, @project.lesson_ids.include?(lesson.id), id: dom_id(lesson) %>
          <%= label_tag dom_id(lesson), lesson.name %> | <%= lesson.date %>
          <br />

        <% end %>
    </div>

  
  <div class="actions">
    <%= f.submit class: "btn btn-green form-control" %>
  </div>
<% end %>

app/views/projects/_related_fields.html.erb
<fieldset>
    <%= f.label :description, "Related Lessons" %><br />
    <%= f.text_area :description, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>   
</fieldset>

app/views/projects/_rubric_fields.html.erb
<fieldset>
    <%= f.label :description, "Rubric" %><br />
    <%= f.text_area :description, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>   
</fieldset>

app/views/projects/edit.html.erb
<div class="container">
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<div class="container">

<% if current_user.try(:admin?) %>
    <%= link_to 'New Project', new_project_path %>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Course Projects</h1>
<% @projects.each do |project| %>

<div class="row">
        <div class="col-md-8">
           
                <h2><%= project.name %></h2>
                <h3>Due: <%= project.due %></h3>

                <td><%= link_to 'Show', project %></td>
      <% if current_user.try(:admin?) %>
         <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

        <br /><br />

                <p><%= simple_format project.description.html_safe %></p>

                <h3>Deliverables</h3>
                <% for deliverable in project.deliverables %>
                <ul><li><%= simple_format deliverable.description.html_safe %></li></ul>
                <% end %>
                

                <h3>Grading Criteria</h3>
                <% for rubric in project.rubrics %>
                <ul><li><%= rubric.description.html_safe %></li></ul>
                <% end %>
        </div>
        <div class="col-md-4 projects-right">
            <div class="padding-right">
            <h1>Related Lessons</h1>
              <% for lesson in project.lessons %>
                <ul>
                  <li>[<%= lesson.date %>] <%= link_to lesson.name, lesson_url(lesson) %>
                    </li>
                </ul>
                <% end %>
            </div>
        </div>
</div>
<br>
<br>
      <%= link_to 'Submit Project', new_submission_path, class: 'btn btn-green' %>

        <hr style ="border-bottom: dotted 1px gray" />
     
    <% end %>

</div>

app/views/projects/new.html.erb
<div class="container">
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container">
<% if flash[:notice] -%>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<div class="row">
<div class="col-md-8">
<% if current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back to All Projects', projects_path %>

  <h1><%= @project.name %></h1>
  <h3>DUE: <%= @project.due %></h3>

  <h2>Description:</h2>
  <p><%= simple_format @project.description.html_safe %></p>


  <h2>Deliverables:</h2>

  <% for deliverable in @project.deliverables %>
        <ul><li><%= simple_format deliverable.description.html_safe %></li></ul>
        <% end %>

        <h2>Grading Criteria:</h2>

  <% for rubric in @project.rubrics %>
        <ul><li><%= rubric.description %></li></ul>
        <% end %>
</div>
<div class="col-md-4 projects-right">
    <div class="padding-right">

  <h1>Related Lessons</h1>
   <% for lesson in @project.lessons %>
                <ul>
                  <li>[<%= lesson.date %>] <%= link_to lesson.name, lesson_url(lesson) %>
                    </li>
                </ul>
                <% end %>
  </div>

  </div>
</div>
      <%= link_to 'Submit Project', new_submission_path, class: 'btn btn-primary' %>

</div>