config/routes.rb
Rails.application.routes.draw do
    resources :slidedecks
  resources :notes
  resources :tutorials
  resources :presentations
  resources :grades
  resources :submissions
  resources :assignments
  resources :abouts
  resources :projects
  resources :courses
  resources :posts do 
    resources :responses
  end

  get 'pages/gradebook'
    get 'pages/graded'

  get 'pages/accounts'
  get 'usergrades' => "submissions#usergrades"
 
  devise_for :users
   match 'users/:id' => 'users#index', via: :get
# or 
get 'users/:id' => 'users#index'
# or
resources :users, only: [:index]

root :to => 'abouts#index'  
resources :lessons
  get 'pages/policies'

if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :presentations
	has_many :objectives, :dependent => :destroy
	has_many :takeaways, :dependent => :destroy
	has_many :readings, :dependent => :destroy
	has_many :homeworks, :dependent => :destroy
	has_many :classactivitys, :dependent => :destroy
	has_many :learnings
	has_many :projects, :through => :learnings
	has_many :presentations, :through => :learnings
	has_many :presentations, :through => :learnings
	has_many :assignments, :through => :learnings
	acts_as_commontable
	
	has_attached_file :document 
		do_not_validate_attachment_file_type :document

	has_attached_file :image
		do_not_validate_attachment_file_type :image


			attr_accessor :delete_image
  			before_validation { image.clear if delete_image == '1' }
  	has_attached_file :document
		  	attr_accessor :delete_document

		    before_validation { document.clear if delete_document == '1' }
		 module DeletableAttachment
		  extend ActiveSupport::Concern

		  included do
		    attachment_definitions.keys.each do |name|

		      attr_accessor :"delete_#{name}"
		      attr_accessible :"delete_#{name}"
		      
		      before_validation { send(name).clear if send("delete_#{name}") == '1' }

		      define_method :"delete_#{name}=" do |value|
		        instance_variable_set :"@delete_#{name}", value
		        send("#{name}_file_name_will_change!")
		      end

		    end
		  end

		end
 
	accepts_nested_attributes_for :objectives, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :readings, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :homeworks, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :classactivitys, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
	accepts_nested_attributes_for :takeaways, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

	belongs_to :user
	belongs_to :course
	acts_as_votable
  	default_scope { order('date') } 
  	  self.per_page = 14

private

  ransacker :week do
    Arel.sql("to_char(\"#{table_name}\".\"id\", '99999')")
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :check_user, only: [:edit, :update, :destroy]
  before_filter :authorize_admin, only: [:new, :create, :destroy, :edit]
  # GET /lessons
  # GET /lessons.json
  def index
  @search = Lesson.search(params[:q])
  @search.sorts = 'date' if @search.sorts.empty?
  @results = @search.result
  @results = @results.where(:lesson_type => "Main") unless params[:q]
  @lessons = @results
  
end


  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @lesson.objectives.build
    @lesson.readings.build
    @lesson.homeworks.build
    @lesson.classactivitys.build

  end

  # GET /lessons/1/edit
  def edit
    
  end
  
  # POST /lessons
  # POST /lessons.json
  def create

   @lesson = Lesson.new(lesson_params)
    @lesson.user_id = current_user.id

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
      

    end
  end
 

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:slidedeck_link, {project_ids: []},{assignment_ids: []}, {presentation_ids: []}, :lesson_type, :delete_document, :delete_image, :project_id, :thread, :course_id, :name, :week, :date, :image, :document, :document2, :attachment,
      objectives_attributes: [:id, :content, :_destroy],  readings_attributes: [:id, :content, :_destroy], takeaways_attributes: [:id, :content, :_destroy], homeworks_attributes: [:id, :content, :_destroy, :assignment_id,{assignment_ids: []}],
      classactivitys_attributes: [:id, :content, :_destroy])

    end
    def check_user
      if current_user == authorize_admin
        redirect_to root_url, alert: "You don't have permission to do that!"
      end 

    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
	def options_for_lesson_type 
		['Main', 'Lab']
	end
	def options_for_week
		['Week 1', 'Week 2', 'Week 3', 'Week 4', 'Week 5','Week 6', 'Week 7', 'Week 8','Week 9', 'Week 10','Week 11','Week 12','Week 13','Week 14','Week 15']
	end
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson, html: { multipart: true }) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="second-form-group">
  <%= f.select :lesson_type, options_for_lesson_type, :prompt => 'Select Class Type' %>
</div>
<div class="first-group-form">
     
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :week %>
      <%= f.text_field :week, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :date %>
 <%= f.text_field :date, class: "form-control", :data => {:provide => "datepicker"} %>    </div>
  </div>

  <div class="second-form-group">
  <h2>Learning Objectives</h2>
  <%= f.fields_for :objectives do |builder| %>
  <%= render 'objective_fields', f:builder %>

  <% end %>
<%= link_to_add_fields "Add Objective", f, :objectives, class: "btn btn-mini btn-info" %>
</div>

<div class="third-form-group">
  <h2>Class Activities</h2>
  <%= f.fields_for :classactivitys do |builder| %>
  <%= render 'classactivity_fields', f:builder %>
  <% end %>
  <%= link_to_add_fields "Add Activity", f, :classactivitys, class: "btn btn-mini btn-info" %>
</div>

<div class="fourth-form-group">
  <h2>Readings</h2>
  <%= f.fields_for :readings do |builder| %>
  <%= render 'reading_fields', f:builder %>
  <% end %>
  <%= link_to_add_fields "Add Reading", f, :readings, class: "btn btn-mini btn-info" %>
</div>

<div class="third-form-group">
  
    <h2>Add Turn-in Assignment</h2>
        <%= hidden_field_tag "lesson[assignment_ids][]", nil %>
        <% Assignment.all.each do |assignment| %>
          <%= check_box_tag "lesson[assignment_ids][]", assignment.id, @lesson.assignment_ids.include?(assignment.id), id: dom_id(assignment) %>
          <%= assignment.assignment_type %> | <%= label_tag dom_id(assignment), assignment.name %> | <%= assignment.deadline %>
          <br />
        <% end %>
    </div>
<div class="fourth-form-group">
  <h2>Other Homework</h2>
  <%= f.fields_for :homeworks do |builder| %>
  <%= render 'homework_fields', f:builder %>
  <% end %>
  <%= link_to_add_fields "Add Homework (not turned in)", f, :homeworks, class: "btn btn-mini btn-info" %>
</div>
  <!-- <div class="fourth-form-group">
      <h2>Takeaways</h2>
      <%= f.fields_for :takeaways do |builder| %>
      <%= render 'takeaway_fields', f:builder %>
      <% end %>
      <%= link_to_add_fields "Add Takeaway", f, :takeaways, class: "btn btn-mini btn-info" %>
</div> 
   <div class="third-form-group">
      <h2>Slidebean Presentation?</h2>
        <%= hidden_field_tag "lesson[presentation_ids][]", nil %>
        <% Presentation.all.each do |presentation| %>
          <%= check_box_tag "lesson[presentation_ids][]", presentation.id, @lesson.presentation_ids.include?(presentation.id), id: dom_id(presentation) %>
          <%= label_tag dom_id(presentation), presentation.name %>
          <br />

        <% end %>
    </div> -->
 <div class="fourth-form-group">
  <h2>Documents</h2>
    <%= f.label :slidedeck_link, "Link to Slidedeck" %><br>
    <%= f.text_field :slidedeck_link, class: "form-control" %>
  <% if @lesson.document.exists? %>
     
      <%= f.check_box :delete_document %> Remove <%= @lesson.document.original_filename %>
  <% else %>
      <%= f.label :document, "Document 1" %>
      <%= f.file_field :document, :class => "form-control-file", class: "form-control" %>

  <% end %>

  <% if @lesson.image.exists? %>

      <%= f.check_box :delete_image %> Remove <%= @lesson.image.original_filename %>
    <% else %>
    <%= f.label :image, "Document 2" %>
    <%= f.file_field :image, :class => "form-control-file", class: "form-control" %>
  <% end %>
  </div>
<div class="third-form-group">
      <h2>Connect lesson to a project</h2>
        <%= hidden_field_tag "lesson[project_ids][]", nil %>
        <% Project.all.each do |project| %>
          <%= check_box_tag "lesson[project_ids][]", project.id, @lesson.project_ids.include?(project.id), id: dom_id(project) %>
          <%= label_tag dom_id(project), project.name %>
          <br />

        <% end %>
    </div>


  <div class="actions">
    <%= f.submit "Create Lesson", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lessons/_homework_fields.html.erb
<fieldset>
<div class="third-form-group">
    

    <%= f.label :content, "Homework" %><br />
    <%= f.text_area :content, class: "form-control" %> 
  	
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/lessons/_reading_fields.html.erb
<fieldset>
    <%= f.label :content, "Reading" %><br />
    <%= f.text_area :content, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>

    <%= link_to "remove", '#', class: "remove_fields" %>


</fieldset>

app/views/lessons/_takeaway_fields.html.erb
<fieldset>
    <%= f.label :content, "Takeaway" %><br />
    <%= f.text_area :content, class: "form-control" %> 
  
    <%= f.hidden_field :_destroy %>
    <%= link_to "remove", '#', class: "remove_fields" %>

</fieldset>

app/views/lessons/edit.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-2">
<h1>You are editing: "<%= @lesson.name %>"</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>
</div>
</div>

app/views/lessons/index.html.erb
<div class="container">
<div class="filter">
  <%= link_to "Main Schedule", lessons_path, class: 'main-button' %>
  <%= link_to "Lab Schedule", "http://tecm3200.herokuapp.com/lessons?utf8=%E2%9C%93&q%5Blesson_type_cont%5D=Lab&commit=Filter", class: 'lab-button' %>
</div>

<div class="table-responsive">
<table class="table table-bordered table-lessons table-striped">
  <thead>
    <tr>
      <th><%= sort_link @search, :lesson_type, "Class Type" %></th>
      <th><%= sort_link @search, :week, "Week" %></th>
      <th><%= sort_link @search, :date, "Date" %></th>
      <th><%= sort_link @search, :name, "Name" %></th>
      <th>Readings</th>
      <th>Homework</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
      <% if lesson.lesson_type == "Main" %>
        <td style ="background: #6EA59F !important; font-size: 1.1rem !important; text-align: center; color: white !important; text-transform: uppercase" class="lesson_type"><%= lesson.lesson_type %></td>
      <% else %>
        <td style ="background: #F2784B !important; font-size: 1.1rem !important; text-align: center; color: white; text-transform: uppercase" class="lesson_type"><%= lesson.lesson_type %></td>
      <% end %>

        <td class="week"><%= link_to lesson.week, lesson %></td>
        <td class="date"><%= link_to lesson.date, lesson %></td>
        <td class="name"><%= link_to [lesson.name].join(" "), lesson %></td>
      <td>
        <ul><% for reading in lesson.readings %><li><%= reading.content.html_safe %></li><%end%></ul>
      </td>

      <td>
          
            <ul>
            <% for homework in lesson.homeworks %>
                <li><%= homework.content.html_safe %></li>
              <% end %>
            <% for assignment in lesson.assignments %>  
                <li><span style="color: #F9690E; font-weight: bold">[Turn In]</span> <%= link_to assignment.name, assignment_url(assignment) %></li>  
            <% end %>
        </ul>
      </td>


        <td><%= link_to lesson do %>
              <i class="material-icons">pageview</i>
          <% end %>
</td>
        <% if current_user.try(:admin?) %>
        <td><%= link_to edit_lesson_path(lesson) do %>
            <i class="material-icons">edit</i>
            <% end %>

        </td>
        <td><%= link_to lesson, method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="material-icons">delete_forever</i>
                      <% end %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<% if current_user.try(:admin?) %>
<%= link_to 'New Lesson', new_lesson_path, class: "btn btn-green" %>
<br><br>
<% end %>

</div>

app/views/lessons/new.html.erb
<div class="row">
<div class="col-md-8 col-md-offset-2">

<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>
</div>
</div>

app/views/lessons/show.html.erb
<div class="container">
<% if flash[:notice] -%>
  <div class = "alert alert-success"><%= flash[:notice] %></div>
<% end %>

	
<div class="row">
	<div class="col-md-8 show-left">
	<% if @lesson.lesson_type == "Lab" %>
	  <h1 style="color: #ecf0f1 !important; background: #F2784B !important; padding: 10px;">Lesson: <%= @lesson.name %> (<%= @lesson.lesson_type %>)</h1>
	<% else %>
		<h1 style="color: #ecf0f1 !important; background: #6FA59F !important; padding: 10px;">Lesson: <%= @lesson.name %> (<%= @lesson.lesson_type %>)</h1>
	<% end %>
	  <h3><%= image_tag 'calendar-show.png' %> Week:
	  <%= @lesson.week %> | <%= @lesson.date %></h3>

		<h3><%= image_tag 'bullets.png' %> Objectives:</h3>
		<ul>
			<% for objective in @lesson.objectives %>
			<li><%= objective.content %></li>
		<% end %>
		</ul>

		<h3><%= image_tag 'checks.png' %> In-Class Activities:</h3>
		<ul>
		<% for classactivity in @lesson.classactivitys.order(:created_at) %>
		<li><%= classactivity.content.html_safe %></li>
		<% end %>
		</ul>
		<h3><%= image_tag 'attachments.png' %> Lesson Attachments:</h3>
				<ul>
				 	<li>Presentation file: <% if @lesson.slidedeck_link? %><%= link_to "Presentation Slides", @lesson.slidedeck_link %>
			      			<% else %>
			      				No Presentation slides for this lesson.
			      			<% end %></li>
				<% if @lesson.document? %>
					<li>Other file(s): <a target=_blank href=" <%= @lesson.document.url %>"><%= @lesson.document.original_filename %></a></li>
					
				<% end %>
					<% if @lesson.image? %>
					<li>Other file(s): <a target=_blank href=" <%= @lesson.image.url %>"><%= @lesson.image.original_filename %></a></li>
				
				<% end %>
				</ul>
</div>
	<div class="col-md-4 projects-right">
		<div class="padding-right">
			<h1>To Do Before Class</h1>
				<h3><%= image_tag 'book.png' %> Readings:</h3>
				<ul>
				<% for reading in @lesson.readings %>
				<li><%= simple_format reading.content.html_safe %></li>
				<% end %>
				</ul>
				<h3><%= image_tag 'assignment.png' %> Homework:</h3>
				<ul>
				<% for homework in @lesson.homeworks %>
				<li><%= simple_format homework.content.html_safe %></li>
				<% end %>
				 <% for assignment in @lesson.assignments %>  
		              <li><span style="color: #F9690E; font-weight: bold">[Turn In]</span> <%= link_to assignment.name, assignment_url(assignment) %></li>
		                
		           <% end %>
				</ul>
				
				<h3><%= image_tag 'arrow.png' %> Related Project(s)</h3>
				 <% for project in @lesson.projects %>
			      	<ul><li><%= link_to project.name, project_url(project) %></li></ul>
			               
			     <% end %>
		</div>
	</div>
</div><!--row-->
<!--
<div class="row">
<input type="checkbox" id="op" class="takeaway"></input>
		<div class="lower">
			  <label for="op">TL;DR</label>
		</div>
			<div class="overlay overlay-hugeinc">
				<label for="op"></label>
					<div class="overlay-container">
						<h1 class="overlay-heading">Cliffs for "<%=@lesson.name %>" on <%= @lesson.date %></h1>
						<ol type= "1"><% for takeaway in @lesson.takeaways %><li><%= takeaway.content %></li><% end %></ul>
					</div>
			</div>

</div> -->

<% if current_user.try(:admin?) %>
	<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<% end %>
	<%= link_to 'Back to all lessons', lessons_path %>


</div>